<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Car & Tenor Report - TimeTraining</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 20px; }
        .header-bar { background: #6f42c1; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .header-bar h2 { margin: 0; font-weight: 700; }
        .header-bar p { margin: 5px 0 0; opacity: 0.9; font-size: 14px; }
        .info-card { background: #f8f9fa; padding: 15px; border-radius: 8px; text-align: center; border: 1px solid #dee2e6; }
        .info-card .number { font-size: 24px; font-weight: 700; color: #6f42c1; }
        .info-card .text { font-size: 12px; color: #6c757d; }
        .car-card { border: 1px solid #dee2e6; border-radius: 8px; padding: 15px; margin-bottom: 15px; background: #fff; }
        .car-card h6 { color: #6f42c1; font-weight: 700; }
        .tenor-badge { display: inline-block; background: #e9ecef; padding: 4px 10px; border-radius: 4px; margin: 3px; font-size: 11px; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 2px solid #dee2e6; font-size: 12px; color: #6c757d; text-align: center; }
        .meta-row { font-size: 13px; color: #6c757d; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header-bar">
        <h2>🚗 TimeTraining Car Rental</h2>
        <p>Professional Car Rental & Financing Solutions</p>
        <h4 class="mt-3">🚘 Car & Tenor Report</h4>
    </div>

    <div class="meta-row">
        <div class="row">
            <div class="col-4">📅 Generated: <strong>{{ $data['generated_at'] }}</strong></div>
            <div class="col-4">👤 Generated by: <strong>{{ $data['generated_by'] }}</strong></div>
            <div class="col-4">📄 Type: <strong>Car Catalog</strong></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-4">
            <div class="info-card">
                <div class="number">{{ $data['summary']['total_cars'] }}</div>
                <div class="text">Total Cars</div>
            </div>
        </div>
        <div class="col-4">
            <div class="info-card">
                <div class="number">{{ $data['summary']['total_brands'] }}</div>
                <div class="text">Total Brands</div>
            </div>
        </div>
        <div class="col-4">
            <div class="info-card">
                <div class="number">{{ $data['summary']['total_tenors'] }}</div>
                <div class="text">Total Tenor Options</div>
            </div>
        </div>
    </div>

    @foreach($data['cars'] as $car)
    <div class="car-card">
        <div class="row">
            <div class="col-8">
                <h6>{{ $car['car'] }}</h6>
                <p class="mb-1"><strong>Brand:</strong> {{ $car['brand'] }}</p>
                <p class="mb-1"><strong>Price:</strong> Rp {{ number_format($car['price'], 0, ',', '.') }}</p>
                <p class="mb-1"><strong>Applications:</strong> {{ $car['total_applications'] }}</p>
                <small class="text-muted">{{ $car['description'] }}</small>
            </div>
            <div class="col-4">
                <strong>Available Tenors:</strong><br>
                @foreach($car['tenors'] as $tenor)
                <span class="tenor-badge">
                    {{ $tenor['month'] }} mo - Rp {{ number_format($tenor['nominal'], 0, ',', '.') }}
                </span>
                @endforeach
            </div>
        </div>
    </div>
    @endforeach

    <div class="footer">
        <p>© {{ date('Y') }} TimeTraining Car Rental. All Rights Reserved.</p>
        <p>This report is generated automatically. For any queries, please contact support.</p>
    </div>
</body>
</html>
