<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Installment Application Report - TimeTraining</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 20px; }
        .header-bar { background: #198754; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .header-bar h2 { margin: 0; font-weight: 700; }
        .header-bar p { margin: 5px 0 0; opacity: 0.9; font-size: 14px; }
        .stat-box { text-align: center; padding: 15px; border-radius: 8px; margin-bottom: 15px; background: #f8f9fa; border: 2px solid #dee2e6; }
        .stat-box .value { font-size: 32px; font-weight: 700; }
        .stat-box .label { font-size: 12px; text-transform: uppercase; color: #6c757d; }
        .table { font-size: 13px; }
        .table thead { background: #198754; color: white; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 2px solid #dee2e6; font-size: 12px; color: #6c757d; text-align: center; }
        .meta-row { font-size: 13px; color: #6c757d; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header-bar">
        <h2>🚗 TimeTraining Car Rental</h2>
        <p>Professional Car Rental & Financing Solutions</p>
        <h4 class="mt-3">📝 Installment Application Report</h4>
    </div>

    <div class="meta-row">
        <div class="row">
            <div class="col-4">📅 Generated: <strong>{{ $data['generated_at'] }}</strong></div>
            <div class="col-4">👤 Generated by: <strong>{{ $data['generated_by'] }}</strong></div>
            <div class="col-4">📄 Type: <strong>Credit Applications</strong></div>
        </div>
    </div>

    <h5 class="mb-3">📊 Application Summary</h5>
    <div class="row">
        <div class="col-3">
            <div class="stat-box">
                <div class="label">Total</div>
                <div class="value text-primary">{{ $data['summary']['total_applications'] }}</div>
            </div>
        </div>
        <div class="col-3">
            <div class="stat-box">
                <div class="label">✅ Approved</div>
                <div class="value text-success">{{ $data['summary']['accepted'] }}</div>
            </div>
        </div>
        <div class="col-3">
            <div class="stat-box">
                <div class="label">❌ Rejected</div>
                <div class="value text-danger">{{ $data['summary']['rejected'] }}</div>
            </div>
        </div>
        <div class="col-3">
            <div class="stat-box">
                <div class="label">⏳ Pending</div>
                <div class="value text-warning">{{ $data['summary']['pending'] }}</div>
            </div>
        </div>
    </div>

    <div class="alert alert-success mt-3">
        <strong>Approval Rate:</strong> {{ $data['summary']['approval_rate'] }}%
    </div>

    <h5 class="mt-4 mb-3">🚘 Applications by Car</h5>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Car Name</th>
                <th>Brand</th>
                <th class="text-center">Total</th>
                <th class="text-center">Approved</th>
                <th class="text-center">Rejected</th>
                <th class="text-center">Pending</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['by_car'] as $car)
            <tr>
                <td>{{ $car->car_name }}</td>
                <td>{{ $car->brand }}</td>
                <td class="text-center"><strong>{{ $car->total }}</strong></td>
                <td class="text-center"><span class="badge bg-success">{{ $car->accepted }}</span></td>
                <td class="text-center"><span class="badge bg-danger">{{ $car->rejected }}</span></td>
                <td class="text-center"><span class="badge bg-warning text-dark">{{ $car->pending }}</span></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>© {{ date('Y') }} TimeTraining Car Rental. All Rights Reserved.</p>
        <p>This report is generated automatically. For any queries, please contact support.</p>
    </div>
</body>
</html>
