<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payment Report - TimeTraining</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 20px; }
        .header-bar { background: #fd7e14; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .header-bar h2 { margin: 0; font-weight: 700; }
        .header-bar p { margin: 5px 0 0; opacity: 0.9; font-size: 14px; }
        .metric-card { background: white; border: 2px solid #dee2e6; border-radius: 10px; padding: 20px; text-align: center; margin-bottom: 15px; }
        .metric-card.primary { border-color: #fd7e14; background: #fff3e0; }
        .metric-value { font-size: 30px; font-weight: 700; color: #fd7e14; }
        .metric-label { font-size: 12px; text-transform: uppercase; color: #6c757d; margin-top: 5px; }
        .progress { height: 25px; border-radius: 12px; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 2px solid #dee2e6; font-size: 12px; color: #6c757d; text-align: center; }
        .meta-row { font-size: 13px; color: #6c757d; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header-bar">
        <h2>🚗 TimeTraining Car Rental</h2>
        <p>Professional Car Rental & Financing Solutions</p>
        <h4 class="mt-3">💰 Payment Collection Report</h4>
    </div>

    <div class="meta-row">
        <div class="row">
            <div class="col-4">📅 Generated: <strong>{{ $data['generated_at'] }}</strong></div>
            <div class="col-4">👤 Generated by: <strong>{{ $data['generated_by'] }}</strong></div>
            <div class="col-4">📄 Type: <strong>Payment Status</strong></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-6">
            <div class="metric-card primary">
                <div class="metric-label">Total Revenue Expected</div>
                <div class="metric-value">Rp {{ number_format($data['summary']['total_amount'], 0, ',', '.') }}</div>
            </div>
        </div>
        <div class="col-6">
            <div class="metric-card primary">
                <div class="metric-label">Total Collected</div>
                <div class="metric-value">Rp {{ number_format($data['summary']['total_paid'], 0, ',', '.') }}</div>
            </div>
        </div>
    </div>

    <div class="alert alert-{{ $data['summary']['collection_rate'] >= 80 ? 'success' : ($data['summary']['collection_rate'] >= 50 ? 'warning' : 'danger') }}">
        <strong>Collection Rate: {{ $data['summary']['collection_rate'] }}%</strong>
    </div>

    <div class="progress mb-4">
        <div class="progress-bar bg-success" style="width: {{ $data['summary']['collection_rate'] }}%">
            {{ $data['summary']['collection_rate'] }}%
        </div>
    </div>

    <div class="row text-center">
        <div class="col-3">
            <div class="card bg-success text-white">
                <div class="card-body">
                    <h3>{{ $data['summary']['paid_count'] }}</h3>
                    <small>✅ Paid</small>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-warning text-dark">
                <div class="card-body">
                    <h3>{{ $data['summary']['unpaid_count'] }}</h3>
                    <small>⏳ Unpaid</small>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-danger text-white">
                <div class="card-body">
                    <h3>{{ $data['summary']['late_count'] }}</h3>
                    <small>⚠️ Late</small>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card bg-info text-white">
                <div class="card-body">
                    <h3>{{ $data['summary']['total_payments'] }}</h3>
                    <small>📋 Total</small>
                </div>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>© {{ date('Y') }} TimeTraining Car Rental. All Rights Reserved.</p>
        <p>This report is generated automatically. For any queries, please contact support.</p>
    </div>
</body>
</html>
