<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Society Report - TimeTraining</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 20px; }
        .header-bar { background: #0dcaf0; color: #000; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .header-bar h2 { margin: 0; font-weight: 700; }
        .header-bar p { margin: 5px 0 0; font-size: 14px; }
        .stat-card { border-radius: 10px; padding: 15px; text-align: center; background: #f8f9fa; border: 1px solid #dee2e6; margin-bottom: 15px; }
        .stat-card .count { font-size: 28px; font-weight: 700; }
        .stat-card .text { font-size: 12px; color: #6c757d; }
        .table { font-size: 12px; }
        .table thead { background: #0dcaf0; color: #000; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 2px solid #dee2e6; font-size: 12px; color: #6c757d; text-align: center; }
        .meta-row { font-size: 13px; color: #6c757d; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header-bar">
        <h2>🚗 TimeTraining Car Rental</h2>
        <p>Professional Car Rental & Financing Solutions</p>
        <h4 class="mt-3">👥 Society Member Report</h4>
    </div>

    <div class="meta-row">
        <div class="row">
            <div class="col-4">📅 Generated: <strong>{{ $data['generated_at'] }}</strong></div>
            <div class="col-4">👤 Generated by: <strong>{{ $data['generated_by'] }}</strong></div>
            <div class="col-4">📄 Type: <strong>Society Data</strong></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-3">
            <div class="stat-card">
                <div class="count text-primary">{{ $data['summary']['total_societies'] }}</div>
                <div class="text">Total Members</div>
            </div>
        </div>
        <div class="col-3">
            <div class="stat-card">
                <div class="count text-success">{{ $data['summary']['validated'] }}</div>
                <div class="text">✅ Validated</div>
            </div>
        </div>
        <div class="col-3">
            <div class="stat-card">
                <div class="count text-warning">{{ $data['summary']['pending_validation'] }}</div>
                <div class="text">⏳ Pending</div>
            </div>
        </div>
        <div class="col-3">
            <div class="stat-card">
                <div class="count text-info">{{ $data['summary']['applied_installment'] }}</div>
                <div class="text">📝 Applied</div>
            </div>
        </div>
    </div>

    <h5 class="mb-3">📋 Society Details</h5>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>ID Card</th>
                <th>Regional</th>
                <th>Status</th>
                <th>Job</th>
                <th class="text-center">Applications</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['societies'] as $society)
            <tr>
                <td><strong>{{ $society['name'] }}</strong></td>
                <td>{{ $society['id_card_number'] }}</td>
                <td>{{ $society['regional'] }}</td>
                <td>
                    @if($society['validation_status'] == 'accepted')
                        <span class="badge bg-success">Accepted</span>
                    @elseif($society['validation_status'] == 'declined')
                        <span class="badge bg-danger">Declined</span>
                    @else
                        <span class="badge bg-warning text-dark">Pending</span>
                    @endif
                </td>
                <td>{{ $society['job'] }}</td>
                <td class="text-center"><strong>{{ $society['total_applications'] }}</strong></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>© {{ date('Y') }} TimeTraining Car Rental. All Rights Reserved.</p>
        <p>This report is generated automatically. For any queries, please contact support.</p>
    </div>
</body>
</html>
