<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Validation Report - TimeTraining</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 20px; }
        .header-bar { background: #0d6efd; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .header-bar h2 { margin: 0; font-weight: 700; }
        .header-bar p { margin: 5px 0 0; opacity: 0.9; font-size: 14px; }
        .stat-card { border-left: 4px solid; border-radius: 6px; padding: 15px; margin-bottom: 15px; background: #f8f9fa; }
        .stat-card.accepted { border-color: #198754; }
        .stat-card.declined { border-color: #dc3545; }
        .stat-card.pending { border-color: #ffc107; }
        .stat-card.total { border-color: #0d6efd; }
        .stat-value { font-size: 28px; font-weight: 700; }
        .stat-label { color: #6c757d; font-size: 13px; text-transform: uppercase; }
        .table { font-size: 13px; }
        .table thead { background: #0d6efd; color: white; }
        .badge-status { font-size: 11px; padding: 5px 10px; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 2px solid #dee2e6; font-size: 12px; color: #6c757d; text-align: center; }
        .meta-row { font-size: 13px; color: #6c757d; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header-bar">
        <h2>🚗 TimeTraining Car Rental</h2>
        <p>Professional Car Rental & Financing Solutions</p>
        <h4 class="mt-3">📋 Validation Report</h4>
    </div>

    <div class="meta-row">
        <div class="row">
            <div class="col-4">📅 Generated: <strong>{{ $data['generated_at'] }}</strong></div>
            <div class="col-4">👤 Generated by: <strong>{{ $data['generated_by'] }}</strong></div>
            <div class="col-4">📄 Type: <strong>Validation Status</strong></div>
        </div>
    </div>

    <h5 class="mb-3">📊 Summary Statistics</h5>
    <div class="row">
        <div class="col-3">
            <div class="stat-card total">
                <div class="stat-label">Total</div>
                <div class="stat-value text-primary">{{ $data['summary']['total_validations'] }}</div>
            </div>
        </div>
        <div class="col-3">
            <div class="stat-card accepted">
                <div class="stat-label">✅ Accepted</div>
                <div class="stat-value text-success">{{ $data['summary']['accepted'] }}</div>
            </div>
        </div>
        <div class="col-3">
            <div class="stat-card declined">
                <div class="stat-label">❌ Declined</div>
                <div class="stat-value text-danger">{{ $data['summary']['declined'] }}</div>
            </div>
        </div>
        <div class="col-3">
            <div class="stat-card pending">
                <div class="stat-label">⏳ Pending</div>
                <div class="stat-value text-warning">{{ $data['summary']['pending'] }}</div>
            </div>
        </div>
    </div>

    <div class="alert alert-info mt-3">
        <strong>Acceptance Rate:</strong> {{ $data['summary']['acceptance_rate'] }}%
    </div>

    <h5 class="mt-4 mb-3">📍 Validations by Regional</h5>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Province</th>
                <th>District</th>
                <th class="text-center">Total</th>
                <th class="text-center">Accepted</th>
                <th class="text-center">Declined</th>
                <th class="text-center">Pending</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['by_regional'] as $regional)
            <tr>
                <td>{{ $regional->province }}</td>
                <td>{{ $regional->district }}</td>
                <td class="text-center"><strong>{{ $regional->total }}</strong></td>
                <td class="text-center"><span class="badge bg-success">{{ $regional->accepted }}</span></td>
                <td class="text-center"><span class="badge bg-danger">{{ $regional->declined }}</span></td>
                <td class="text-center"><span class="badge bg-warning text-dark">{{ $regional->pending }}</span></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>© {{ date('Y') }} TimeTraining Car Rental. All Rights Reserved.</p>
        <p>This report is generated automatically. For any queries, please contact support.</p>
    </div>
</body>
</html>
